// SPDX-License-Identifier: MIT
// Copyright (c) 2026 WoozyMasta
// Source: github.com/woozymasta/schemadoc

package schemadoc

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math"
	"math/big"
	"sort"
	"strconv"
	"strings"
)

// Options configures markdown rendering behavior.
//
// This model is part of the public contract and is exported as JSON Schema.
type Options struct {
	// Title is the top-level markdown heading.
	//
	// This value is rendered as `# <title>`.
	Title string `json:"title,omitempty" jsonschema:"default=schema reference,minLength=1,example=schema reference,example=My Project Config Reference"`

	// Description is optional top-level document description under title.
	Description string `json:"description,omitempty" jsonschema:"example=Generated reference for runtime configuration schema."`

	// SourcePath is metadata shown in the document header.
	//
	// It does not affect schema parsing, only rendered output.
	SourcePath string `json:"source_path,omitempty" jsonschema:"example=internal/config/schema.json,example=schemas/project.schema.json"`

	// TemplateName selects one built-in template.
	TemplateName string `json:"template_name,omitempty" jsonschema:"default=list,enum=list,enum=table,enum=html,example=list,example=table,example=html"`

	// TemplateText overrides built-in templates with custom template text.
	//
	// Use this for project-specific output layouts.
	TemplateText string `json:"template_text,omitempty" jsonschema:"example=# {{ .Title }}\n\nGenerated by custom template."`

	// AutoGeneratedNote is available to templates for an optional generated-file note.
	//
	// The template chooses the output-specific comment syntax.
	// An empty value uses the default schemadoc note.
	AutoGeneratedNote string `json:"auto_generated_note,omitempty" jsonschema:"example=Generated by schemadoc."`

	// ListMarker defines unordered markdown list marker used during description normalization.
	ListMarker string `json:"list_marker,omitempty" jsonschema:"default=*,enum=-,enum=*,example=*,example=-"`

	// ExampleMode controls property coverage for optional embedded example payload in markdown templates.
	ExampleMode ExampleMode `json:"example_mode,omitempty" jsonschema:"enum=all,enum=required,example=all,example=required"`

	// ExampleFormat enables optional embedded example payload in markdown templates and selects encoding.
	//
	// Empty value disables example embedding.
	ExampleFormat ExampleFormat `json:"example_format,omitempty" jsonschema:"enum=json,enum=yaml,example=json,example=yaml"`

	// FooterToolName is optional footer tool label for rendered documents.
	FooterToolName string `json:"footer_tool_name,omitempty" jsonschema:"example=schemadoc,example=lintkit"`

	// FooterToolURL is optional footer tool project URL.
	FooterToolURL string `json:"footer_tool_url,omitempty" jsonschema:"format=uri,example=https://github.com/woozymasta/schemadoc"`

	// FooterVersion is optional footer build version.
	FooterVersion string `json:"footer_version,omitempty" jsonschema:"example=v0.2.0,example=dev"`

	// FooterCommit is optional footer build commit.
	FooterCommit string `json:"footer_commit,omitempty" jsonschema:"example=abcdef1,example=unknown"`

	// ExampleOptions configures embedded example formatting.
	ExampleOptions ExampleOptions `json:"example_options"`

	// WrapWidth defines word-wrap width for plain description paragraphs.
	//
	// Markdown structures such as lists, blockquotes, and fenced code blocks are preserved.
	WrapWidth int `json:"wrap_width,omitempty" jsonschema:"default=80,minimum=1,example=80,example=100"`

	// HideExtraKeywords hides "Other keywords" attribute rows in rendered docs.
	//
	// Internal keywords such as `x-order` are hidden regardless of this option.
	HideExtraKeywords bool `json:"hide_extra_keywords,omitempty" jsonschema:"default=false"`

	// ShowInternalKeywords includes renderer-specific schema keywords in docs.
	ShowInternalKeywords bool `json:"show_internal_keywords,omitempty" jsonschema:"default=false"`
}

// DraftInfo describes detected JSON Schema draft support status.
type DraftInfo struct {
	// Raw is the original `$schema` value from input.
	Raw string `json:"raw,omitempty" jsonschema:"example=https://json-schema.org/draft/2020-12/schema"`

	// Canonical is normalized draft alias (for example `2020-12`).
	Canonical string `json:"canonical,omitempty" jsonschema:"example=2020-12,example=draft-07"`

	// Supported reports whether draft is recognized by the renderer.
	Supported bool `json:"supported" jsonschema:"default=false"`
}

// SchemaModel is the schema root for public package models.
//
// The generator CLI (`schemadoc-schema`) reflects this type into JSON Schema.
type SchemaModel struct {
	// DraftInfo is the normalized output of draft detection.
	DraftInfo DraftInfo `json:"draft_info" jsonschema:"required"`

	// Options configures markdown generation.
	Options Options `json:"options" jsonschema:"required"`
}

// schemaDocument is the normalized JSON Schema root model used by renderer.
type schemaDocument struct {
	Root        schemaValue
	Raw         any
	Defs        map[string]schemaValue
	RawKeywords map[string]any
	Schema      string
	ID          string
	Ref         string
	Dialect     schemaDialect
	Draft       DraftInfo
}

// schemaValue stores either boolean schema or object schema.
type schemaValue struct {
	Bool   *bool
	Object map[string]any
}

// isZero reports whether schema value contains neither bool nor object schema.
func (value schemaValue) isZero() bool {
	return value.Bool == nil && value.Object == nil
}

// parseDocument decodes raw schema bytes into normalized schemaDocument model.
func parseDocument(schemaBytes []byte) (schemaDocument, error) {
	var root any
	if err := decodeJSONWithNumbers(schemaBytes, &root); err != nil {
		return schemaDocument{}, fmt.Errorf("%w: %w", ErrDecodeSchema, err)
	}

	rootValue, ok := toSchemaValue(root)
	if !ok {
		return schemaDocument{}, fmt.Errorf("%w: got %T", ErrSchemaRootType, root)
	}

	doc := schemaDocument{
		Root: rootValue,
		Raw:  root,
	}

	if rootObject := rootValue.Object; rootObject != nil {
		doc.RawKeywords = rootObject
		doc.Schema = asString(rootObject["$schema"])
		doc.ID = firstNonEmpty(asString(rootObject["$id"]), asString(rootObject["id"]))
		doc.Ref = asString(rootObject["$ref"])
		doc.Defs = mergeDefinitions(rootObject)
		doc.Draft = detectDraft(doc.Schema)
		doc.Dialect = normalizeSchemaDialect(doc.Schema)
		return doc, nil
	}

	doc.Draft = detectDraft("")
	doc.Dialect = normalizeSchemaDialect("")
	return doc, nil
}

// decodeJSONWithNumbers decodes JSON without reducing numbers to float64.
func decodeJSONWithNumbers(content []byte, target any) error {
	decoder := json.NewDecoder(bytes.NewReader(content))
	decoder.UseNumber()
	if err := decoder.Decode(target); err != nil {
		return err
	}

	var extra any
	err := decoder.Decode(&extra)
	switch {
	case errors.Is(err, io.EOF):
		return nil
	case err == nil:
		return errors.New("multiple JSON values")
	default:
		return err
	}
}

// mergeDefinitions merges legacy and modern definition maps into one normalized map.
func mergeDefinitions(root map[string]any) map[string]schemaValue {
	out := make(map[string]schemaValue)
	addDefinitionMap(out, root["definitions"])
	addDefinitionMap(out, root["$defs"])
	return out
}

// addDefinitionMap adds valid schema entries from raw map into target definition map.
func addDefinitionMap(target map[string]schemaValue, raw any) {
	values, ok := raw.(map[string]any)
	if !ok {
		return
	}

	for key, item := range values {
		value, ok := toSchemaValue(item)
		if !ok {
			continue
		}

		target[key] = value
	}
}

// toSchemaValue converts bool/object raw values to normalized schemaValue.
func toSchemaValue(value any) (schemaValue, bool) {
	switch typed := value.(type) {
	case bool:
		flag := typed
		return schemaValue{Bool: &flag}, true
	case map[string]any:
		return schemaValue{Object: typed}, true
	default:
		return schemaValue{}, false
	}
}

// mapSchemaValues converts raw map values to schemaValue entries and drops invalid values.
func mapSchemaValues(value any) map[string]schemaValue {
	rawMap, ok := value.(map[string]any)
	if !ok {
		return nil
	}

	out := make(map[string]schemaValue, len(rawMap))
	for key, raw := range rawMap {
		schema, ok := toSchemaValue(raw)
		if !ok {
			continue
		}

		out[key] = schema
	}

	return out
}

// asString converts raw value to trimmed string or empty string for non-strings.
func asString(value any) string {
	text, ok := value.(string)
	if !ok {
		return ""
	}

	return strings.TrimSpace(text)
}

// asBool converts raw value to bool with conversion status.
func asBool(value any) (bool, bool) {
	flag, ok := value.(bool)
	return flag, ok
}

// asSlice converts raw value to []any slice or nil if type is different.
func asSlice(value any) []any {
	items, ok := value.([]any)
	if !ok {
		return nil
	}

	return items
}

// asStringSlice converts []any value to []string while dropping non-string entries.
func asStringSlice(value any) []string {
	items, ok := value.([]any)
	if !ok {
		return nil
	}

	out := make([]string, 0, len(items))
	for _, item := range items {
		text, ok := item.(string)
		if !ok {
			continue
		}

		out = append(out, text)
	}

	return out
}

// asNumber converts numeric JSON-like values to float64.
func asNumber(value any) (float64, bool) {
	switch typed := value.(type) {
	case float64:
		return typed, !math.IsNaN(typed) && !math.IsInf(typed, 0)

	case float32:
		floatValue := float64(typed)
		return floatValue, !math.IsNaN(floatValue) && !math.IsInf(floatValue, 0)

	case int:
		return float64(typed), true
	case int8:
		return float64(typed), true
	case int16:
		return float64(typed), true
	case int32:
		return float64(typed), true
	case int64:
		return float64(typed), true
	case uint:
		return float64(typed), true
	case uint8:
		return float64(typed), true
	case uint16:
		return float64(typed), true
	case uint32:
		return float64(typed), true
	case uint64:
		return float64(typed), true

	case json.Number:
		floatValue, err := typed.Float64()
		if err != nil {
			return 0, false
		}

		return floatValue, !math.IsNaN(floatValue) && !math.IsInf(floatValue, 0)

	case string:
		text := strings.TrimSpace(typed)
		if text == "" {
			return 0, false
		}

		floatValue, err := strconv.ParseFloat(text, 64)
		if err != nil {
			return 0, false
		}

		return floatValue, !math.IsNaN(floatValue) && !math.IsInf(floatValue, 0)

	default:
		return 0, false
	}
}

// asExactNumber converts JSON numeric values to an exact rational number.
// Strings are intentionally excluded
// because JSON numeric equality does not coerce strings into numbers.
func asExactNumber(value any) (*big.Rat, bool) {
	switch typed := value.(type) {
	case json.Number:
		return exactNumberFromText(typed.String())

	case float64:
		if math.IsNaN(typed) || math.IsInf(typed, 0) {
			return nil, false
		}
		return exactNumberFromText(strconv.FormatFloat(typed, 'g', -1, 64))

	case float32:
		floatValue := float64(typed)
		if math.IsNaN(floatValue) || math.IsInf(floatValue, 0) {
			return nil, false
		}
		return exactNumberFromText(strconv.FormatFloat(floatValue, 'g', -1, 32))

	case int:
		return new(big.Rat).SetInt64(int64(typed)), true
	case int8:
		return new(big.Rat).SetInt64(int64(typed)), true
	case int16:
		return new(big.Rat).SetInt64(int64(typed)), true
	case int32:
		return new(big.Rat).SetInt64(int64(typed)), true
	case int64:
		return new(big.Rat).SetInt64(typed), true
	case uint:
		return exactUnsignedNumber(uint64(typed)), true
	case uint8:
		return exactUnsignedNumber(uint64(typed)), true
	case uint16:
		return exactUnsignedNumber(uint64(typed)), true
	case uint32:
		return exactUnsignedNumber(uint64(typed)), true
	case uint64:
		return exactUnsignedNumber(typed), true

	default:
		return nil, false
	}
}

// exactNumberFromText parses a decimal or scientific JSON number exactly.
func exactNumberFromText(text string) (*big.Rat, bool) {
	text = strings.TrimSpace(text)
	if text == "" {
		return nil, false
	}

	number, ok := new(big.Rat).SetString(text)
	return number, ok
}

// exactUnsignedNumber converts an unsigned integer without an intermediate float.
func exactUnsignedNumber(value uint64) *big.Rat {
	return new(big.Rat).SetInt(new(big.Int).SetUint64(value))
}

// sortedKeys returns deterministic sorted keys for string map.
func sortedKeys(values map[string]any) []string {
	out := make([]string, 0, len(values))
	for key := range values {
		out = append(out, key)
	}

	sort.Strings(out)
	return out
}

// firstNonEmpty returns first non-empty trimmed string from input list.
func firstNonEmpty(values ...string) string {
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value != "" {
			return value
		}
	}

	return ""
}
