// SPDX-License-Identifier: MIT
// Copyright (c) 2026 WoozyMasta
// Source: github.com/woozymasta/schemadoc

package schemadoc

import (
	"strings"
	"testing"
)

func TestNormalizeTableCell(t *testing.T) {
	t.Parallel()

	value := "`# {{ .Title }}\n\nGenerated by custom | template.`"
	got := normalizeTableCell(value)
	want := "`# {{ .Title }} Generated by custom \\| template.`"
	if got != want {
		t.Fatalf("normalizeTableCell() = %q, want %q", got, want)
	}
}

func TestRenderInlineMarkdownHTML(t *testing.T) {
	t.Parallel()

	input := "[`draft_info`](#schemamodeldraftinfo).`canonical`"
	got := renderInlineMarkdownHTML(input)

	want := "<a href=\"#schemamodeldraftinfo\"><code>draft_info</code></a>.<code>canonical</code>"
	if got != want {
		t.Fatalf("renderInlineMarkdownHTML() = %q, want %q", got, want)
	}
}

func TestRenderInlineMarkdownHTMLRejectsUnsafeLinks(t *testing.T) {
	t.Parallel()

	input := "[click](javascript:alert(1))"
	got := renderInlineMarkdownHTML(input)

	if strings.Contains(got, "<a href=") {
		t.Fatalf("renderInlineMarkdownHTML() created unsafe anchor: %q", got)
	}
}

func TestRenderInlineMarkdownHTMLMultiLineCodeSpan(t *testing.T) {
	t.Parallel()

	input := "`# {{ .Title }}\n\nGenerated by custom template.`"
	got := renderInlineMarkdownHTML(input)
	want := "<code># {{ .Title }}<br><br>Generated by custom template.</code>"
	if got != want {
		t.Fatalf("renderInlineMarkdownHTML() = %q, want %q", got, want)
	}
}

func TestRenderMarkdownBlockHTMLSupportsLists(t *testing.T) {
	t.Parallel()

	input := "TemplateName selects one built-in template.\n\nSupported values:\n\n* `list`\n* `table`\n* `html`"
	got := renderMarkdownBlockHTML(input)

	assertContains(t, got, "<p>TemplateName selects one built-in template.</p>")
	assertContains(t, got, "<p>Supported values:</p>")
	assertContains(t, got, "<ul><li><code>list</code></li><li><code>table</code></li><li><code>html</code></li></ul>")
}

func TestRenderAttributeValueHTMLUsesPreForMultilineCodeSpan(t *testing.T) {
	t.Parallel()

	input := "`# {{ .Title }}\n\nGenerated by custom template.`"
	got := renderAttributeValueHTML(input)
	want := "<pre><code># {{ .Title }}\n\nGenerated by custom template.</code></pre>"
	if got != want {
		t.Fatalf("renderAttributeValueHTML() = %q, want %q", got, want)
	}
}

func TestRenderAttributeValueHTMLKeepsInlineCode(t *testing.T) {
	t.Parallel()

	input := "`list`"
	got := renderAttributeValueHTML(input)
	want := "<code>list</code>"
	if got != want {
		t.Fatalf("renderAttributeValueHTML() = %q, want %q", got, want)
	}
}
