// SPDX-License-Identifier: MIT
// Copyright (c) 2026 WoozyMasta
// Source: github.com/woozymasta/schemadoc

package schemadoc

import "testing"

func TestNormalizeTableCell(t *testing.T) {
	t.Parallel()

	value := "`# {{ .Title }}\n\nGenerated by custom | template.`"
	got := normalizeTableCell(value)
	want := "`# {{ .Title }} Generated by custom \\| template.`"
	if got != want {
		t.Fatalf("normalizeTableCell() = %q, want %q", got, want)
	}
}
