// SPDX-License-Identifier: MIT
// Copyright (c) 2026 WoozyMasta
// Source: github.com/woozymasta/schemadoc

package main

import (
	"bytes"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func run(args []string, stdout, stderr io.Writer) int {
	return runWithIO(args, os.Stdin, stdout, stderr)
}

func TestCLI_Schema2Doc(t *testing.T) {
	t.Parallel()

	schemaPath := repoTestdataPath(t, "generated", "app.schema.json")
	customTemplatePath := filepath.Join(t.TempDir(), "custom.gotmpl")
	if err := os.WriteFile(
		customTemplatePath,
		[]byte("# custom\n{{ range .Definitions }}- {{ .Name }}\n{{ end }}\n"),
		0o600,
	); err != nil {
		t.Fatalf("write custom template: %v", err)
	}

	testCases := []struct {
		name        string
		args        []string
		stdin       io.Reader
		outFile     string
		code        int
		stdoutHas   []string
		stdoutNoHas []string
		stderrHas   []string
		fileHas     []string
		fileNoHas   []string
	}{
		{
			name:      "default to stdout",
			args:      []string{"schema2doc", schemaPath},
			code:      0,
			stdoutHas: []string{"# schema reference"},
		},
		{
			name:      "table template",
			args:      []string{"schema2doc", "--template", "table", schemaPath},
			code:      0,
			stdoutHas: []string{"| Attribute | Value |"},
		},
		{
			name:      "html template",
			args:      []string{"schema2doc", "--template", "html", schemaPath},
			code:      0,
			stdoutHas: []string{"<!DOCTYPE html>"},
		},
		{
			name: "stdin schema",
			args: []string{"schema2doc"},
			stdin: strings.NewReader(`{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:test",
  "type": "object",
  "properties": { "name": { "type": "string" } }
}`),
			code:        0,
			stdoutHas:   []string{"## Root"},
			stdoutNoHas: []string{"Source schema:"},
		},
		{
			name:    "write output file",
			args:    []string{"schema2doc", "--title", "Custom Doc", schemaPath},
			outFile: filepath.Join(t.TempDir(), "schema.md"),
			code:    0,
			fileHas: []string{"# Custom Doc"},
		},
		{
			name:      "custom description",
			args:      []string{"schema2doc", "--description", "Generated by CI.", schemaPath},
			code:      0,
			stdoutHas: []string{"Generated by CI."},
		},
		{
			name:      "custom template file",
			args:      []string{"schema2doc", "--template-file", customTemplatePath, schemaPath},
			code:      0,
			stdoutHas: []string{"# custom"},
		},
		{
			name: "wrap width and list marker normalization",
			args: []string{"schema2doc", "--wrap", "24", "--list-marker", "*"},
			stdin: strings.NewReader(`{
  "$schema":"https://json-schema.org/draft/2020-12/schema",
  "type":"object",
  "properties":{"template_name":{"type":"string","description":"Supported values:\n\n - list\n - table"}}
}`),
			code:        0,
			stdoutHas:   []string{"* list"},
			stdoutNoHas: []string{"\n - list"},
		},
		{
			name:      "embedded required yaml example",
			args:      []string{"schema2doc", "--mode", "required", "--format", "yaml", schemaPath},
			code:      0,
			stdoutHas: []string{"## Example yaml document", "```yaml", "name: demo-service", "retry:"},
			stdoutNoHas: []string{
				"mode:",
			},
		},
	}

	for index := range testCases {
		testCase := testCases[index]
		t.Run(testCase.name, func(t *testing.T) {
			var stdout bytes.Buffer
			var stderr bytes.Buffer
			args := append([]string{}, testCase.args...)
			if testCase.outFile != "" {
				args = append(args, testCase.outFile)
			}

			code := runWithIO(args, firstReader(testCase.stdin), &stdout, &stderr)
			if code != testCase.code {
				t.Fatalf("run exit code = %d, want %d; stderr: %s", code, testCase.code, stderr.String())
			}

			checkContainsAll(t, stderr.String(), testCase.stderrHas)
			checkContainsAll(t, stdout.String(), testCase.stdoutHas)
			checkNotContainsAny(t, stdout.String(), testCase.stdoutNoHas)

			if testCase.outFile != "" {
				data, err := os.ReadFile(testCase.outFile)
				if err != nil {
					t.Fatalf("read output file: %v", err)
				}

				content := string(data)
				checkContainsAll(t, content, testCase.fileHas)
				checkNotContainsAny(t, content, testCase.fileNoHas)
				if stdout.Len() != 0 {
					t.Fatalf("stdout should be empty for file output, got: %s", stdout.String())
				}
			}
		})
	}
}

func TestCLI_Schema2ExamplesAndTemplateAndConfig(t *testing.T) {
	t.Parallel()

	schemaPath := repoTestdataPath(t, "generated", "app.schema.json")
	jsonOut := filepath.Join(t.TempDir(), "required.json")
	yamlOut := filepath.Join(t.TempDir(), "required.yaml")

	testCases := []struct {
		name      string
		args      []string
		code      int
		stdoutHas []string
		stderrHas []string
	}{
		{
			name:      "template stdout",
			args:      []string{"template"},
			code:      0,
			stdoutHas: []string{"# {{ .Title }}"},
		},
		{
			name:      "config stdout",
			args:      []string{"config", "--mode", "all"},
			code:      0,
			stdoutHas: []string{"schema:"},
		},
		{
			name:      "schema2json stdout",
			args:      []string{"schema2json", schemaPath},
			code:      0,
			stdoutHas: []string{`"name": "demo-service"`, `"mode": "safe"`},
		},
		{
			name: "schema2json required file",
			args: []string{"schema2json", "--mode", "required", schemaPath, jsonOut},
			code: 0,
		},
		{
			name: "schema2yaml required file",
			args: []string{"schema2yaml", "--mode", "required", schemaPath, yamlOut},
			code: 0,
		},
	}

	for index := range testCases {
		testCase := testCases[index]
		t.Run(testCase.name, func(t *testing.T) {
			var stdout bytes.Buffer
			var stderr bytes.Buffer
			code := run(testCase.args, &stdout, &stderr)
			if code != testCase.code {
				t.Fatalf("run exit code = %d, want %d; stderr: %s", code, testCase.code, stderr.String())
			}

			checkContainsAll(t, stdout.String(), testCase.stdoutHas)
			checkContainsAll(t, stderr.String(), testCase.stderrHas)
		})
	}

	requiredJSON, err := os.ReadFile(jsonOut)
	if err != nil {
		t.Fatalf("read required json: %v", err)
	}

	checkContainsAll(t, string(requiredJSON), []string{
		`"name": "demo-service"`,
		`"retry": {`,
		`"shared": {`,
	})
	checkNotContainsAny(t, string(requiredJSON), []string{`"mode": "safe"`})

	requiredYAML, err := os.ReadFile(yamlOut)
	if err != nil {
		t.Fatalf("read required yaml: %v", err)
	}

	checkContainsAll(t, string(requiredYAML), []string{
		"# Service Name",
		"# Human-readable service name.",
		"name: demo-service",
		"# TLS Enabled",
		"# Enable TLS for outbound connections.",
		"enabled: true",
	})
}

func TestCLI_ConfigExampleOrderAndComments(t *testing.T) {
	t.Parallel()

	var stdout bytes.Buffer
	var stderr bytes.Buffer

	code := run([]string{"config"}, &stdout, &stderr)
	if code != 0 {
		t.Fatalf("run exit code = %d, want 0; stderr: %s", code, stderr.String())
	}

	output := stdout.String()
	checkContainsAll(t, output, []string{
		"# Schema is working schema path for the whole document pipeline.",
		"schema: schema.json",
		"check: false",
		"mod2schema:",
		"merge:",
		"schema2json:",
		"schema2doc:",
		"schema2yaml:",
		"output: <string>",
	})

	order := []string{
		"schema: schema.json",
		"check: false",
		"mod2schema:",
		"merge:",
		"schema2json:",
		"schema2doc:",
		"schema2yaml:",
	}

	last := -1
	for _, marker := range order {
		index := strings.Index(output, marker)
		if index < 0 {
			t.Fatalf("marker %q not found in output", marker)
		}

		if index <= last {
			t.Fatalf("marker %q is out of order", marker)
		}

		last = index
	}
}

func TestResolveBuildConfigPath(t *testing.T) {
	t.Parallel()

	if got := resolveBuildConfigPath(""); got != "schemadoc.build.yaml" {
		t.Fatalf("resolveBuildConfigPath(\"\") = %q, want %q", got, "schemadoc.build.yaml")
	}

	if got := resolveBuildConfigPath(" custom.yaml "); got != "custom.yaml" {
		t.Fatalf("resolveBuildConfigPath(\" custom.yaml \") = %q, want %q", got, "custom.yaml")
	}
}

func TestCLI_ModCommands(t *testing.T) {
	t.Parallel()

	moduleRoot := findModuleRoot(t)
	schemaOut := filepath.Join(t.TempDir(), "mod.schema.json")
	schemaYAMLOut := filepath.Join(t.TempDir(), "mod.schema.yaml")
	mdOut := filepath.Join(t.TempDir(), "mod.md")

	testCases := []struct {
		name      string
		args      []string
		code      int
		stdoutHas []string
		stderrHas []string
	}{
		{
			name:      "mod2schema stdout",
			args:      []string{"mod2schema", "--type", "SchemaModel", moduleRoot},
			code:      0,
			stdoutHas: []string{`"SchemaModel"`},
		},
		{
			name: "mod2schema file",
			args: []string{"mod2schema", "--type", "SchemaModel", moduleRoot, schemaOut},
			code: 0,
		},
		{
			name: "mod2schema yaml file",
			args: []string{"mod2schema", "--type", "SchemaModel", moduleRoot, schemaYAMLOut},
			code: 0,
		},
		{
			name: "mod2doc stdout",
			args: []string{"mod2doc", "--type", "SchemaModel", moduleRoot},
			code: 0, stdoutHas: []string{"# schema reference", "## Options"},
		},
		{
			name: "mod2doc file",
			args: []string{"mod2doc", "--type", "SchemaModel", "--title", "Schema Model", moduleRoot, mdOut},
			code: 0,
		},
		{
			name:      "invalid type",
			args:      []string{"mod2schema", "--type", "Schema-Model", moduleRoot},
			code:      1,
			stderrHas: []string{"run module schema generator:"},
		},
	}

	for index := range testCases {
		testCase := testCases[index]
		t.Run(testCase.name, func(t *testing.T) {
			var stdout bytes.Buffer
			var stderr bytes.Buffer
			code := run(testCase.args, &stdout, &stderr)
			if code != testCase.code {
				t.Fatalf("run exit code = %d, want %d; stderr: %s", code, testCase.code, stderr.String())
			}

			checkContainsAll(t, stdout.String(), testCase.stdoutHas)
			checkContainsAll(t, stderr.String(), testCase.stderrHas)
		})
	}

	schemaContent, err := os.ReadFile(schemaOut)
	if err != nil {
		t.Fatalf("read mod schema: %v", err)
	}
	checkContainsAll(t, string(schemaContent), []string{`"Options"`})

	schemaYAMLContent, err := os.ReadFile(schemaYAMLOut)
	if err != nil {
		t.Fatalf("read mod yaml schema: %v", err)
	}
	checkContainsAll(t, string(schemaYAMLContent), []string{"$defs:", "Options:"})
	checkNotContainsAny(t, string(schemaYAMLContent), []string{`"$defs"`})

	mdContent, err := os.ReadFile(mdOut)
	if err != nil {
		t.Fatalf("read mod markdown: %v", err)
	}
	checkContainsAll(t, string(mdContent), []string{"# Schema Model"})
}

func TestCLI_BuildAndMergeAndErrors(t *testing.T) {
	t.Parallel()

	schemaPath := repoTestdataPath(t, "generated", "app.schema.json")
	tempDir := t.TempDir()
	firstOut := filepath.Join(tempDir, "first.json")
	secondOut := filepath.Join(tempDir, "second.json")
	buildConfig := filepath.Join(tempDir, "build.yaml")
	buildConfigBody := strings.Join([]string{
		"schema: " + filepath.ToSlash(schemaPath),
		"schema2json:",
		"  output: " + filepath.ToSlash(firstOut),
		"---",
		"schema: " + filepath.ToSlash(schemaPath),
		"schema2json:",
		"  output: " + filepath.ToSlash(secondOut),
		"  mode: required",
		"",
	}, "\n")
	if err := os.WriteFile(buildConfig, []byte(buildConfigBody), 0o600); err != nil {
		t.Fatalf("write build config: %v", err)
	}

	invalidConfig := filepath.Join(tempDir, "invalid.yaml")
	if err := os.WriteFile(invalidConfig, []byte("schema2json:\n  output: out.json\n"), 0o600); err != nil {
		t.Fatalf("write invalid config: %v", err)
	}

	basePath := filepath.Join(tempDir, "base.schema.json")
	addonPath := filepath.Join(tempDir, "addon.schema.json")
	mergeOut := filepath.Join(tempDir, "merged.schema.json")
	if err := os.WriteFile(
		basePath,
		[]byte(`{"$schema":"https://json-schema.org/draft/2020-12/schema","$defs":{"Base":{"type":"object"}}}`),
		0o600,
	); err != nil {
		t.Fatalf("write base schema: %v", err)
	}
	if err := os.WriteFile(
		addonPath,
		[]byte(`{"$schema":"https://json-schema.org/draft/2020-12/schema","$defs":{"Linting_RunPolicyConfig":{"type":"object"}}}`),
		0o600,
	); err != nil {
		t.Fatalf("write addon schema: %v", err)
	}

	testCases := []struct {
		name      string
		args      []string
		code      int
		stderrHas []string
	}{
		{
			name: "build index 0 all docs",
			args: []string{"build", buildConfig},
			code: 0,
		},
		{
			name: "build index 1",
			args: []string{"build", buildConfig, "--index", "1"},
			code: 0,
		},
		{
			name:      "build index out of range",
			args:      []string{"build", buildConfig, "--index", "4"},
			code:      1,
			stderrHas: []string{"out of range"},
		},
		{
			name:      "build validation error",
			args:      []string{"build", invalidConfig},
			code:      1,
			stderrHas: []string{"validate config"},
		},
		{
			name: "merge defs",
			args: []string{"merge", basePath, mergeOut, "--merge-defs=/$defs=" + addonPath + "#/$defs"},
			code: 0,
		},
		{
			name: "missing command",
			args: []string{},
			code: 2,
		},
		{
			name:      "unknown template choice",
			args:      []string{"template", "--template", "missing"},
			code:      2,
			stderrHas: []string{"Invalid value"},
		},
		{
			name:      "missing schema file",
			args:      []string{"schema2doc", filepath.Join(tempDir, "missing.json")},
			code:      1,
			stderrHas: []string{"read schema input:"},
		},
		{
			name:      "unknown draft warning",
			args:      []string{"schema2doc", writeSchemaFixture(t, "https://json-schema.org/draft/2099-01/schema")},
			code:      0,
			stderrHas: []string{"warning: unsupported $schema value"},
		},
	}

	for index := range testCases {
		testCase := testCases[index]
		t.Run(testCase.name, func(t *testing.T) {
			var stdout bytes.Buffer
			var stderr bytes.Buffer
			code := run(testCase.args, &stdout, &stderr)
			if code != testCase.code {
				t.Fatalf("run exit code = %d, want %d; stderr: %s", code, testCase.code, stderr.String())
			}

			checkContainsAll(t, stderr.String(), testCase.stderrHas)
		})
	}

	if _, err := os.Stat(firstOut); err != nil {
		t.Fatalf("first build output missing: %v", err)
	}
	if _, err := os.Stat(secondOut); err != nil {
		t.Fatalf("second build output missing: %v", err)
	}

	mergeContent, err := os.ReadFile(mergeOut)
	if err != nil {
		t.Fatalf("read merged schema: %v", err)
	}
	checkContainsAll(t, string(mergeContent), []string{`"Linting_RunPolicyConfig"`})
}

func TestCLI_BuildCheckMode(t *testing.T) {
	t.Parallel()

	schemaPath := repoTestdataPath(t, "generated", "app.schema.json")
	tempDir := t.TempDir()
	jsonOut := filepath.Join(tempDir, "example.json")
	mdOut := filepath.Join(tempDir, "schema.md")

	generatedJSONBytes, err := os.ReadFile(
		repoTestdataPath(t, "generated", "app.config.json"),
	)
	if err != nil {
		t.Fatalf("read generated json fixture: %v", err)
	}

	generatedJSON := string(generatedJSONBytes)
	if err := os.WriteFile(jsonOut, []byte(generatedJSON), 0o600); err != nil {
		t.Fatalf("write json output fixture: %v", err)
	}

	if err := os.WriteFile(mdOut, []byte("# stale\n"), 0o600); err != nil {
		t.Fatalf("write markdown output fixture: %v", err)
	}

	configPath := filepath.Join(tempDir, "build-check.yaml")
	configBody := strings.Join([]string{
		"check: true",
		"schema: " + filepath.ToSlash(schemaPath),
		"schema2json:",
		"  output: " + filepath.ToSlash(jsonOut),
		"schema2doc:",
		"  output: " + filepath.ToSlash(mdOut),
		"",
	}, "\n")
	if err := os.WriteFile(configPath, []byte(configBody), 0o600); err != nil {
		t.Fatalf("write build check config: %v", err)
	}

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	code := run([]string{"build", configPath}, &stdout, &stderr)
	if code != 1 {
		t.Fatalf("run exit code = %d, want 1; stderr: %s", code, stderr.String())
	}

	checkContainsAll(t, stderr.String(), []string{"content differs"})
}

func TestCLI_BuildDerivesOutputPaths(t *testing.T) {
	t.Parallel()

	tempDir := t.TempDir()
	schemaPath := filepath.Join(tempDir, "config.schema.json")
	schemaFixture, err := os.ReadFile(repoTestdataPath(t, "generated", "app.schema.json"))
	if err != nil {
		t.Fatalf("read schema fixture: %v", err)
	}

	if err := os.WriteFile(schemaPath, schemaFixture, 0o600); err != nil {
		t.Fatalf("write schema fixture copy: %v", err)
	}

	configPath := filepath.Join(tempDir, "build-derived.yaml")
	configBody := strings.Join([]string{
		"schema: " + filepath.ToSlash(schemaPath),
		"schema2json: {}",
		"schema2yaml: {}",
		"schema2doc: {}",
		"---",
		"schema: " + filepath.ToSlash(schemaPath),
		"schema2doc:",
		"  template: table",
		"---",
		"schema: " + filepath.ToSlash(schemaPath),
		"schema2doc:",
		"  template: html",
		"",
	}, "\n")
	if err := os.WriteFile(configPath, []byte(configBody), 0o600); err != nil {
		t.Fatalf("write build config: %v", err)
	}

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	code := run([]string{"build", configPath}, &stdout, &stderr)
	if code != 0 {
		t.Fatalf("run exit code = %d, want 0; stderr: %s", code, stderr.String())
	}

	base := strings.TrimSuffix(schemaPath, filepath.Ext(schemaPath))
	expectedOutputs := []string{
		base + ".json",
		base + ".yaml",
		base + ".list.md",
		base + ".table.md",
		base + ".html",
	}
	for _, path := range expectedOutputs {
		if _, err := os.Stat(path); err != nil {
			t.Fatalf("expected derived output %q: %v", path, err)
		}
	}
}

func firstReader(reader io.Reader) io.Reader {
	if reader != nil {
		return reader
	}

	return os.Stdin
}

func findModuleRoot(t *testing.T) string {
	t.Helper()

	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("get working dir: %v", err)
	}

	for {
		candidate := filepath.Join(dir, "go.mod")
		if _, err := os.Stat(candidate); err == nil {
			return dir
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}

		dir = parent
	}

	t.Fatal("module root with go.mod was not found")
	return ""
}

func writeSchemaFixture(t *testing.T, schemaURI string) string {
	t.Helper()

	dir := t.TempDir()
	path := filepath.Join(dir, "schema.json")
	body := `{
  "$schema": "` + schemaURI + `",
  "$id": "urn:test",
  "$ref": "#/$defs/Config",
  "$defs": {
    "Config": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      }
    }
  }
}`
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatalf("write schema fixture: %v", err)
	}

	return path
}

func repoTestdataPath(t *testing.T, parts ...string) string {
	t.Helper()

	all := append([]string{findModuleRoot(t), "testdata"}, parts...)
	return filepath.Join(all...)
}

func checkContainsAll(t *testing.T, value string, expects []string) {
	t.Helper()

	for index := range expects {
		if !strings.Contains(value, expects[index]) {
			t.Fatalf("missing substring %q in:\n%s", expects[index], value)
		}
	}
}

func checkNotContainsAny(t *testing.T, value string, unexpected []string) {
	t.Helper()

	for index := range unexpected {
		if strings.Contains(value, unexpected[index]) {
			t.Fatalf("unexpected substring %q in:\n%s", unexpected[index], value)
		}
	}
}
