// SPDX-License-Identifier: MIT
// Copyright (c) 2026 WoozyMasta
// Source: github.com/woozymasta/schemadoc

package main

import (
	"fmt"

	"github.com/woozymasta/flags"
)

// applyCommandLongDescriptions configures detailed command help text.
func applyCommandLongDescriptions(parser *flags.Parser) {
	descriptions := commandLongDescriptions()
	for commandName, description := range descriptions {
		command := parser.Find(commandName)
		if command == nil {
			continue
		}

		command.LongDescription = description
	}
}

// commandLongDescriptions builds detailed help text by command.
func commandLongDescriptions() map[string]string {
	const programName = flags.DocProgramNamePlaceholder

	return map[string]string{
		"template": fmt.Sprintf(`
Print built-in template text (list, table, or html).
Use it as a starting point for a custom template file.

Examples:

  - %[1]s template > list.gotmpl
  - %[1]s template -t table templates/table.gotmpl
  - %[1]s template -t html templates/reference.html.gotmpl
`, programName),

		"schema2doc": fmt.Sprintf(`
Generate markdown or HTML docs from JSON Schema (--template).
Reads schema from file argument or stdin; writes output to file argument or stdout.
Use --format json|yaml to append example payload code block at the end.

Examples:

  - %[1]s schema2doc schema.json > schema.md
  - cat schema.json | %[1]s schema2doc -t table > schema.table.md
  - %[1]s schema2doc -t html --description "Generated by CI." schema.json > schema.html
  - %[1]s schema2doc --mode required --format yaml schema.json > schema.with-example.md
`, programName),

		"schema2json": fmt.Sprintf(`
Generate example JSON payload from JSON Schema.
Reads schema from file argument or stdin; writes JSON to file argument or stdout.

Examples:

  - %[1]s schema2json schema.json > example.json
  - %[1]s schema2json --mode required schema.json example.required.json
`, programName),

		"schema2yaml": fmt.Sprintf(`
Generate example YAML payload from JSON Schema.
Reads schema from file argument or stdin; writes YAML to file argument or stdout.

Examples:

  - %[1]s schema2yaml schema.json > example.yaml
  - %[1]s schema2yaml --mode all schema.json example.all.yaml
`, programName),

		"mod2schema": fmt.Sprintf(`
Generate JSON Schema from Go type.
Pass local module dir or remote module@version as positional argument.
Use --package when type lives outside module root package.
Target package must be importable (package main is not supported).

Examples:

  - %[1]s mod2schema --type Config . > schema.json
  - %[1]s mod2schema --package github.com/acme/project/internal/config --type Config github.com/acme/project@v1.2.3 schema.json
  - %[1]s mod2schema --type Config --key-namer snake github.com/acme/project@latest > schema.snake.json
`, programName),

		"mod2doc": fmt.Sprintf(`
Generate docs directly from Go type.
This is mod2schema`+`schema2doc in one command.
Use the same module/package/type selection rules as mod2schema.
Target package must be importable (package main is not supported).
Use --format json|yaml to append example payload code block at the end.

Examples:

  - %[1]s mod2doc --type Config . > model.md
  - %[1]s mod2doc -t table --type Config github.com/acme/project@v1.2.3 docs/model.table.md
  - %[1]s mod2doc -t html --description "Generated by CI." --type Config github.com/acme/project@v1.2.3 > model.html
  - %[1]s mod2doc --mode required --format json --type Config github.com/acme/project@v1.2.3 > model.with-example.md
  - %[1]s mod2doc --type Config --key-namer snake . > model.snake.md
`, programName),

		"merge": fmt.Sprintf(`
Merge JSON Schema documents.
Supports direct map flags (--replace/--merge/--merge-defs) and config file (--config).

Examples:

  - %[1]s merge base.schema.json out.schema.json --merge-defs '/$defs=lint.schema.json#/$defs'
  - %[1]s merge --config schema-merge.yaml --inplace
  - %[1]s merge --config schema-merge.yaml --check
`, programName),

		"build": fmt.Sprintf(`
Run jobs from YAML config.
When config path is omitted, ./schemadoc.build.yaml is used.
Index mode:

  - --index 0 runs all documents in order.
  - --index 1..N runs selected document.

Examples:

  - %[1]s build
  - %[1]s build schemadoc.build.yaml --index 1
`, programName),

		"config": fmt.Sprintf(`
Generate config example. Useful for quick start and CI bootstrap.

Examples:

  - %[1]s config > schemadoc.build.yaml
  - %[1]s config --mode required > schemadoc.build.min.yaml
`, programName),
	}
}
