// SPDX-License-Identifier: MIT
// Copyright (c) 2026 WoozyMasta
// Source: github.com/woozymasta/schemadoc

package main

import "github.com/woozymasta/flags"

// configureDescriptions installs user-facing command descriptions and examples.
func configureDescriptions(parser *flags.Parser, options *cliOptions) {
	parser.SetLongDescription(`{{.ProgramBaseName}} helps you build JSON Schema, docs, and example configs.

You can generate docs from schema files, reflect Go types into schema,
merge schema fragments, and run multi-step jobs from config.`)

	setCommandDescription(parser, &options.Template,
		"Print built-in template text",
		"Print built-in list, table, or HTML template text. Use it as a starting point for a custom template file.",
		flags.Example().
			Raw(">").
			Arg("list.gotmpl"),
		flags.Example().
			Option(&options.Template.TemplateFlags.TemplateName, "table").
			Raw(">").
			Arg("table.gotmpl"),
		flags.Example().
			Option(&options.Template.TemplateFlags.TemplateName, "html").
			Raw(">").
			Arg("reference.html.gotmpl"))

	setCommandDescription(parser, &options.SchemaToDoc,
		"Generate docs from JSON Schema",
		`Generate Markdown or HTML documentation from JSON Schema.
Reads schema from a file or stdin and writes output to a file or stdout.
Use --format json|yaml to append an example payload.`,
		flags.Example().
			Arg("schema.json").
			Raw(">").
			Arg("schema.md"),
		flags.Example().
			Raw("cat").
			Arg("schema.json").
			Raw("|").
			Option(&options.SchemaToDoc.TemplateFlags.TemplateName, "table").
			Raw(">").
			Arg("schema.table.md"),
		flags.Example().
			Option(&options.SchemaToDoc.TemplateFlags.TemplateName, "html").
			Option(&options.SchemaToDoc.RenderFlags.Description, "Generated by CI.").
			Arg("schema.json").
			Raw(">").
			Arg("schema.html"),
		flags.Example().
			Option(&options.SchemaToDoc.ExampleFlags.Mode, "required").
			Option(&options.SchemaToDoc.ExampleFlags.Format, "yaml").
			Arg("schema.json").
			Raw(">").
			Arg("schema.with-example.md"))

	setCommandDescription(parser, &options.SchemaToJSON,
		"Generate example JSON",
		`Generate an example JSON payload from JSON Schema.
Reads schema from a file or stdin and writes JSON to a file or stdout.`,
		flags.Example().
			Arg("schema.json").
			Raw(">").
			Arg("example.json"),
		flags.Example().
			Option(&options.SchemaToJSON.ExampleFlags.Mode, "required").
			Arg("schema.json").
			Arg("example.required.json"))

	setCommandDescription(parser, &options.SchemaToYAML,
		"Generate example YAML",
		`Generate an example YAML payload from JSON Schema.
Reads schema from a file or stdin and writes YAML to a file or stdout.`,
		flags.Example().
			Arg("schema.json").
			Raw(">").
			Arg("example.yaml"),
		flags.Example().
			Option(&options.SchemaToYAML.ExampleFlags.Mode, "all").
			Arg("schema.json").
			Arg("example.all.yaml"))

	setCommandDescription(parser, &options.ModuleToSchema,
		"Generate JSON Schema from Go",
		"Generate JSON Schema from a Go type. The target package must be importable; package main is not supported.",
		flags.Example().
			Option(&options.ModuleToSchema.ModuleFlags.TypeName, "Config").
			Arg(".").
			Raw(">").
			Arg("schema.json"),
		flags.Example().
			Option(&options.ModuleToSchema.ModuleFlags.PackagePath, "github.com/acme/project/internal/config").
			Option(&options.ModuleToSchema.ModuleFlags.TypeName, "Config").
			Arg("github.com/acme/project@v1.2.3").
			Arg("schema.json"),
		flags.Example().
			Option(&options.ModuleToSchema.ModuleFlags.TypeName, "Config").
			Option(&options.ModuleToSchema.ModuleFlags.KeyNamer, "snake").
			Arg("github.com/acme/project@latest").
			Raw(">").
			Arg("schema.snake.json"))

	setCommandDescription(parser, &options.ModuleToMarkdown,
		"Generate docs from Go",
		`Generate documentation directly from a Go type using the same module,
package, and type selection rules as mod2schema.`,
		flags.Example().
			Option(&options.ModuleToMarkdown.ModuleFlags.TypeName, "Config").
			Arg(".").
			Raw(">").
			Arg("model.md"),
		flags.Example().
			Option(&options.ModuleToMarkdown.TemplateFlags.TemplateName, "table").
			Option(&options.ModuleToMarkdown.ModuleFlags.TypeName, "Config").
			Arg("github.com/acme/project@v1.2.3").
			Arg("docs/model.table.md"),
		flags.Example().
			Option(&options.ModuleToMarkdown.TemplateFlags.TemplateName, "html").
			Option(&options.ModuleToMarkdown.RenderFlags.Description, "Generated by CI.").
			Option(&options.ModuleToMarkdown.ModuleFlags.TypeName, "Config").
			Arg("github.com/acme/project@v1.2.3").
			Raw(">").
			Arg("model.html"),
		flags.Example().
			Option(&options.ModuleToMarkdown.ExampleFlags.Mode, "required").
			Option(&options.ModuleToMarkdown.ExampleFlags.Format, "json").
			Option(&options.ModuleToMarkdown.ModuleFlags.TypeName, "Config").
			Arg("github.com/acme/project@v1.2.3").
			Raw(">").
			Arg("model.with-example.md"),
		flags.Example().
			Option(&options.ModuleToMarkdown.ModuleFlags.TypeName, "Config").
			Option(&options.ModuleToMarkdown.ModuleFlags.KeyNamer, "snake").
			Arg(".").
			Raw(">").
			Arg("model.snake.md"))

	setCommandDescription(parser, &options.SchemaMerge,
		"Merge JSON Schema documents",
		"Merge JSON Schema documents using direct map flags or a merge configuration file.",
		flags.Example().
			Arg("base.schema.json").
			Arg("out.schema.json").
			Option(&options.SchemaMerge.MergeFlags.MergeDefs, "/$defs=lint.schema.json#/$defs"),
		flags.Example().
			Option(&options.SchemaMerge.MergeFlags.ConfigPath, "schema-merge.yaml").
			Raw("--inplace"),
		flags.Example().
			Option(&options.SchemaMerge.MergeFlags.ConfigPath, "schema-merge.yaml").
			Raw("--check"))

	setCommandDescription(parser, &options.Build,
		"Run build jobs",
		`Run jobs from a YAML config. When omitted, the config path defaults to
./schemadoc.build.yaml; index 0 runs all documents.`,
		flags.Example(),
		flags.Example().
			Arg("schemadoc.build.yaml").
			Option(&options.Build.ConfigIndex, "1"))

	setCommandDescription(parser, &options.Config,
		"Generate build config",
		"Generate a build config example for quick start and CI bootstrap.",
		flags.Example().
			Raw(">").
			Arg("schemadoc.build.yaml"),
		flags.Example().
			Option(&options.Config.Mode, "required").
			Raw(">").
			Arg("schemadoc.build.min.yaml"))
}

// setCommandDescription applies a description and structured examples to one
// registered command and fails fast when the command model is inconsistent.
func setCommandDescription(parser *flags.Parser, target any, short, long string, examples ...*flags.CommandExample) {
	command, err := parser.CommandFor(target)
	if err != nil {
		panic(err)
	}

	command.SetShortDescription(short)
	command.SetLongDescription(long)
	if err := command.SetExamples(examples...); err != nil {
		panic(err)
	}
}
