// SPDX-License-Identifier: MIT
// Copyright (c) 2026 WoozyMasta
// Source: github.com/woozymasta/schemadoc

package main

import (
	"fmt"
	"strings"

	"github.com/jessevdk/go-flags"
)

// applyCommandLongDescriptions configures detailed command help text with examples.
func applyCommandLongDescriptions(parser *flags.Parser, programName string) {
	descriptions := map[string]string{
		"template": strings.TrimSpace(fmt.Sprintf(`
Print built-in markdown template text (`+"`list` or `table`"+`).
Use it as a starting point for a custom template file.

Examples:
> $ %s template > list.gotmpl
> $ %s template -t table templates/table.gotmpl
> $ %s template -t html templates/reference.html.gotmpl
`, programName, programName, programName)),
		"schema2md": strings.TrimSpace(fmt.Sprintf(`
Convert JSON Schema to markdown.
Reads schema from file argument or stdin; writes markdown to file argument or stdout.
Use --format json|yaml to append example payload code block at the end.

Examples:
> $ %s schema2md schema.json > schema.md
> $ cat schema.json | %s schema2md -t table > schema.table.md
> $ %s schema2md -t html --description "Generated by CI." schema.json > schema.html
> $ %s schema2md --mode required --format yaml schema.json > schema.with-example.md
`, programName, programName, programName, programName)),
		"schema2json": strings.TrimSpace(fmt.Sprintf(`
Generate example JSON payload from schema.
Reads schema from file argument or stdin; writes JSON to file argument or stdout.

Examples:
> $ %s schema2json schema.json > example.json
> $ %s schema2json --mode required schema.json example.required.json
`, programName, programName)),
		"schema2yaml": strings.TrimSpace(fmt.Sprintf(`
Generate example YAML payload from schema.
Reads schema from file argument or stdin; writes YAML to file argument or stdout.

Examples:
> $ %s schema2yaml schema.json > example.yaml
> $ %s schema2yaml --mode all schema.json example.all.yaml
`, programName, programName)),
		"mod2schema": strings.TrimSpace(fmt.Sprintf(`
Reflect Go type into JSON Schema.
Use module import path as positional argument.
Use --module-root for local module directory and --package when type is not in module root package.

Examples:
> $ %s mod2schema --module-root . --type Config github.com/acme/project > schema.json
> $ %s mod2schema --module-root . --package github.com/acme/project/internal/config --type Config github.com/acme/project schema.json
> $ %s mod2schema --module-root . --type Config --key-namer snake github.com/acme/project > schema.snake.json
`, programName, programName, programName)),
		"mod2md": strings.TrimSpace(fmt.Sprintf(`
Generate markdown directly from Go type.
This is `+"`mod2schema` + `schema2md`"+` in one command.
Use the same module/package/type selection rules as `+"`mod2schema`"+`.
Use --format json|yaml to append example payload code block at the end.

Examples:
> $ %s mod2md --module-root . --type Config github.com/acme/project > model.md
> $ %s mod2md -t table --module-root . --type Config github.com/acme/project docs/model.table.md
> $ %s mod2md -t html --description "Generated by CI." --module-root . --type Config github.com/acme/project > model.html
> $ %s mod2md --mode required --format json --module-root . --type Config github.com/acme/project > model.with-example.md
> $ %s mod2md --module-root . --type Config --key-namer snake github.com/acme/project > model.snake.md
`, programName, programName, programName, programName, programName)),
	}

	for commandName, description := range descriptions {
		command := parser.Find(commandName)
		if command == nil {
			continue
		}

		command.LongDescription = description
	}
}
